server:
  port: 8085
spring:
  application:
    name: SpringCloud-uploadfiles
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
upload:
  qiniu:
    ak: wOmKWeQMrIx2pqZp_gmY9N30hhiUydeCTTBMGhqg
    sk: cD_8v56o0PVXpowQgQhEOJ3su4DvkUmElCplDHZN
    bucketname: as3
    url: qfkpavppd.hd-bkt.clouddn.com



